spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/quiz_db
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
#logging:
#  level:
#    root: debug
#    ru:
#      ayubdzhanov:
#        javaquiz: debug